# Generated by Django 6.1 on 2026-09-02 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_fee'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='orders.order'),
        ),
    ]
