# Generated by Django 6.1 on 2026-09-02 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_refundrequest_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='refund_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='payments.refundrequest'),
        ),
    ]
