# Generated by Django 6.1 on 2026-09-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_financialtransaction_refund_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='payout_failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
