# Generated by Django 6.1 on 2026-09-03 11:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_refundrequest_payout_failure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='reserved_available_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='reserved_pending_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
