# Generated by Django 6.1 on 2026-09-04 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_refundrequest_reserved_available_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.OneToOneField(limit_choices_to={'role__in': ['shop_owner', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='financial_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role__in': ['shop_owner', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
