# Generated by Django 6.1 on 2026-09-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_walletdeposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale_pending', 'Sale Pending'), ('sale_released', 'Sale Released'), ('commission', 'Admin Commission'), ('refund', 'Customer Refund'), ('deposit', 'Wallet Deposit'), ('withdrawal', 'Shop Owner Withdrawal'), ('refund_reversal', 'Refund Reversal'), ('withdrawal_reversal', 'Withdrawal Reversal'), ('adjustment', 'Financial Adjustment')], max_length=30),
        ),
    ]
