# Generated by Django 6.1 on 2026-09-10 10:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_withdrawalrequest_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='held_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale_pending', 'Sale Pending'), ('sale_released', 'Sale Released'), ('commission', 'Admin Commission'), ('refund', 'Customer Refund'), ('deposit', 'Wallet Deposit'), ('withdrawal', 'Shop Owner Withdrawal'), ('refund_reversal', 'Refund Reversal'), ('withdrawal_reversal', 'Withdrawal Reversal'), ('purchase_hold', 'Purchase Held'), ('purchase_refund', 'Purchase Refund'), ('adjustment', 'Financial Adjustment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.OneToOneField(limit_choices_to={'role__in': ['customer', 'shop_owner', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='financial_wallet', to=settings.AUTH_USER_MODEL),
        ),
    ]
