# Generated by Django 6.1 on 2026-09-17 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_period', models.CharField(choices=[('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month'), ('year', 'Per Year')], default='year', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rents/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='rents/videos/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending_owner', 'Pending Owner Confirmation'), ('owner_confirmed', 'Owner Confirmed'), ('owner_rejected', 'Owner Rejected'), ('customer_cancelled', 'Customer Cancelled'), ('completed', 'Completed')], default='pending_owner', max_length=30)),
                ('owner_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('owner_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('customer_cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_bookings', to=settings.AUTH_USER_MODEL)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rents.rent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
