# Generated by Django 6.1 on 2026-09-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0002_rentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='owner_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
