# Generated by Django 6.1 on 2026-09-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0003_rent_owner_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rentbooking',
            name='owner_cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentbooking',
            name='status',
            field=models.CharField(choices=[('pending_owner', 'Pending Owner Confirmation'), ('owner_confirmed', 'Owner Confirmed'), ('owner_rejected', 'Owner Rejected'), ('owner_cancelled', 'Owner Cancelled'), ('customer_cancelled', 'Customer Cancelled'), ('completed', 'Completed')], default='pending_owner', max_length=30),
        ),
    ]
