# Generated by Django 6.1 on 2026-09-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0004_rent_quantity_rentbooking_owner_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentbooking',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentbooking',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'MUA Wallet'), ('paystack', 'Paystack')], default='wallet', max_length=20),
        ),
        migrations.AddField(
            model_name='rentbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='paid', max_length=20),
        ),
        migrations.AddField(
            model_name='rentbooking',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rentbooking',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentbooking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending_owner', 'Pending Owner Confirmation'), ('owner_confirmed', 'Owner Confirmed'), ('owner_rejected', 'Owner Rejected'), ('owner_cancelled', 'Owner Cancelled'), ('customer_cancelled', 'Customer Cancelled'), ('completed', 'Completed')], default='pending_owner', max_length=30),
        ),
    ]
