# Generated by Django 6.1 on 2026-09-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0005_rentbooking_paid_at_rentbooking_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentbooking',
            name='paystack_refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rentbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded')], default='paid', max_length=20),
        ),
    ]
