# Generated by Django 6.1 on 2026-09-29 16:47

import config.cloudinary_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0006_rentbooking_paystack_refund_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=config.cloudinary_storages.CloudinaryImageStorage(), upload_to='rents/images/'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='video',
            field=models.FileField(blank=True, null=True, storage=config.cloudinary_storages.CloudinaryVideoStorage(), upload_to='rents/videos/'),
        ),
        migrations.AlterField(
            model_name='rentimage',
            name='image',
            field=models.ImageField(storage=config.cloudinary_storages.CloudinaryImageStorage(), upload_to='rents/images/'),
        ),
    ]
