# Generated by Django 6.1 on 2026-09-29 16:47

import config.cloudinary_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=config.cloudinary_storages.CloudinaryImageStorage(), upload_to='profiles/'),
        ),
    ]
