# Generated by Django 6.1 on 2026-09-29 16:47

import config.cloudinary_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=config.cloudinary_storages.CloudinaryImageStorage(), upload_to='shops/logos/'),
        ),
    ]
