# Generated by Django 6.1 on 2026-09-29 16:47

import config.cloudinary_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_image_message_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=config.cloudinary_storages.CloudinaryImageStorage(), upload_to='messaging/images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, storage=config.cloudinary_storages.CloudinaryVideoStorage(), upload_to='messaging/videos/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='voice_note',
            field=models.FileField(blank=True, null=True, storage=config.cloudinary_storages.CloudinaryVideoStorage(), upload_to='messaging/voice_notes/'),
        ),
    ]
