# Generated by Django 6.1 on 2026-09-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='social/videos/'),
        ),
    ]
