# Generated by Django 6.1 on 2026-09-29 16:47

import config.cloudinary_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_socialactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=config.cloudinary_storages.CloudinaryImageStorage(), upload_to='social/images/'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='video',
            field=models.FileField(blank=True, null=True, storage=config.cloudinary_storages.CloudinaryVideoStorage(), upload_to='social/videos/'),
        ),
    ]
