# Generated by Django 6.1 on 2026-08-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('received', 'Received'), ('rejected', 'Rejected')], default='waiting', max_length=20),
        ),
    ]
