# Generated by Django 6.1 on 2026-09-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_stock_restored'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_channel',
            field=models.CharField(blank=True, choices=[('card', 'Card'), ('ussd', 'USSD')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('paystack', 'Paystack'), ('cash', 'Cash on Delivery'), ('bank', 'Bank Transfer')], max_length=20),
        ),
    ]
