# Generated by Django 6.1 on 2026-09-15 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_customer_product_alter_orderitem_product'),
        ('products', '0004_customerproduct_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='customer_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_order_items', to='products.customerproduct'),
        ),
    ]
