# Generated by Django 6.1 on 2026-09-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='customer_products/videos/'),
        ),
    ]
