# Generated by Django 6.1 on 2026-09-15 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_customerproduct_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.customerproduct')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('product__isnull', False), ('customer_product__isnull', False), _connector='OR'), name='product_image_has_parent'), models.CheckConstraint(condition=models.Q(('product__isnull', True), ('customer_product__isnull', True), _connector='OR'), name='product_image_one_parent_only')],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('values', models.JSONField(default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('customer_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='products.customerproduct')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('product__isnull', False), ('customer_product__isnull', False), _connector='OR'), name='product_option_has_parent'), models.CheckConstraint(condition=models.Q(('product__isnull', True), ('customer_product__isnull', True), _connector='OR'), name='product_option_one_parent_only')],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('option_values', models.JSONField(default=dict)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='products.customerproduct')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='products.product')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('product__isnull', False), ('customer_product__isnull', False), _connector='OR'), name='product_variant_has_parent'), models.CheckConstraint(condition=models.Q(('product__isnull', True), ('customer_product__isnull', True), _connector='OR'), name='product_variant_one_parent_only')],
            },
        ),
    ]
