# Generated by Django 6.1 on 2026-09-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage_productoption_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
