# Generated by Django 6.1 on 2026-09-29 16:47

import config.cloudinary_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=config.cloudinary_storages.CloudinaryImageStorage(), upload_to='customer_products/images/'),
        ),
        migrations.AlterField(
            model_name='customerproduct',
            name='video',
            field=models.FileField(blank=True, null=True, storage=config.cloudinary_storages.CloudinaryVideoStorage(), upload_to='customer_products/videos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=config.cloudinary_storages.CloudinaryImageStorage(), upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, storage=config.cloudinary_storages.CloudinaryVideoStorage(), upload_to='products/videos/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=config.cloudinary_storages.CloudinaryImageStorage(), upload_to='products/gallery/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=config.cloudinary_storages.CloudinaryImageStorage(), upload_to='products/variants/'),
        ),
    ]
